version: "4.0"

services:
  postgres:
    container_name: postgres
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    networks:
      - audio-meta-service-network

networks:
  audio-meta-service-network:

volumes:
  postgres-storage: